<div class="card"> <!-- syntaxe vient de bootstrap/ documentation / component / cards -->
    <div class="card-header">
        Ecrit le <?= $article['created_at']; ?>
    </div>
    <div class="card-body">
        <h5 class="card-title"><?= $article['title']; ?></h5>
        <p class="card-text"><?= $article['teaser']; ?></p>
        <a href="#" class="btn btn-primary">Read more</a>
    </div>
</div>