<?php include THEME_PATH . DS . 'header.phtml'; ?>
<?php include THEME_PATH . DS . 'navbar.phtml'; ?>

<style>
    <?php include THEME_PATH .DS . 'css' . DS . 'new.css'; ?>
</style>

<div class="container">
    <h1>Articles</h1>


    <?php foreach ($articles as $article) : ?>
        <?php include THEME_PATH . DS . 'article.phtml'; ?>
    <?php endforeach; ?>

</div>

<?php include THEME_PATH . DS . 'footer.phtml'; ?>


