<?php include THEME_PATH . DS . 'header.phtml';?>

<style>
    <?php include THEME_PATH .DS . 'css' . DS . 'signin.css'; ?>
</style>




    <form class="form-signin text-center" method="POST">
        <h2 class="form-signin-heading">Enregistrer vous ici</h2>
        <label for="username" class="sr-only">Pseudo</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Pseudo" required autofocus>
        <label for="password" class="sr-only">Mot de passe</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Mot de passe" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Se souvenir de moi
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Connexion</button>
        <p class="mt-5 mb-3 text-muted">&copy;<?= date('Y')?></p>
    </form>



<?php include THEME_PATH . DS . 'footer.phtml';?>
