<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<?= BASE_URL ?>">Mon Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse container-fluid" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <?php if (isset($_SESSION['user'])) : ?>
            <li class="dropdown">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-astronaut" href="#"></i>
                    <?= ucfirst($_SESSION['user']['username']); ?>
                </button>
                <div class="dropdown dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#"><i class="fas fa-users"></i> Mon compte </a> <!--Les <i></i> sont les liens des icones de fontawesome -->
                    <a class="dropdown-item" href="#"><i class="fas fa-user-circle"></i>   Préférences </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="logout.php"><i class="fas fa-sign-out-alt"></i> Déconnexion </a>
                </div>
            </li>
            <?php else : ?>
                <li class="nav-item">
                    <a class="nav-link" href="login.php"><i class="fas fa-user-astronaut"></i> Connexion </a></a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>
