<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<?= BASE_URL ?>"><img src="https://usercontent1.hubstatic.com/7193144.png" width="60px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse container-fluid" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <?php if (isset($_SESSION['user'])) : ?>
                <li class="nav-item">
                <a class="nav-link" href="<?= BASE_URL; ?>/dashboard">Tableau de bord</a>
                </li>
                <?php endif ?>
            <?php if (!isset($_SESSION['user'])) : ?>
                <a class="nav-link" href="<?php BASE_URL; ?>/Php-Blogger/blog.php">Blog<span class="sr-only">(current)</span></a>
            </li>
            <?php else : ?>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Blog
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?= BASE_URL; ?>/blog.php">Consulter les articles</a>
                    <a class="dropdown-item" href="<?= BASE_URL; ?>/blog/mes-articles.php">Mes articles</a>
                    <a class="dropdown-item" href="<?= BASE_URL; ?>/blog/add-article.php">Ajouter un article</a>
                </div>
            </li>
            <?php endif; ?>
        </ul>
        <ul class="navbar-nav">
            <?php if (isset($_SESSION['user'])) : ?>
            <li class="dropdown">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="https://vignette.wikia.nocookie.net/piratesonline/images/0/09/OSTSkullTransparent.png/revision/latest/scale-to-width-down/467?cb=20120224191146" width="30px" href="#">
                    <?= ucfirst($_SESSION['user']['username']); ?>
                </button>
                <div class="dropdown dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#"><i class="fas fa-users"></i> Mon compte </a> <!--Les <i></i> sont les liens des icones de fontawesome -->
                    <a class="dropdown-item" href="#"><i class="fas fa-user-circle"></i>   Préférences </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?= BASE_URL; ?>/logout.php"><i class="fas fa-sign-out-alt"></i> Déconnexion </a>
                </div>
            </li>
            <?php else : ?>
                <li class="nav-item">
                    <a class="nav-link" href="registration.php"><img src="https://fr.seaicons.com/wp-content/uploads/2016/03/wheel-icon-1.png" width="30px" href="#"> Inscription </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="login.php"><img src="https://vignette.wikia.nocookie.net/piratesonline/images/0/09/OSTSkullTransparent.png/revision/latest/scale-to-width-down/467?cb=20120224191146" width="30px" href="#"> Connexion </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>
