<?php include THEME_PATH . DS . 'header.phtml'; ?>
<?php include THEME_PATH . DS . 'navbar.phtml'; ?>
<style>
    <?php include THEME_PATH .DS . 'css' . DS . 'new.css'; ?>
</style>

<div class="container">
    <h1 class="mt-3 mb-3"><?= $title ?></h1>


    <?php foreach ($articles as $article) : ?>
        <?php include THEME_PATH . DS . 'article.phtml'; ?>
    <?php endforeach; ?>


<?php include THEME_PATH . DS . 'footer.phtml'; ?>
